/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package presentation;

import persistence.IDaoClient;
import persistence.IDaoCommande;
import persistence.IDaoFacture;
import persistence.IDaoProduit;
import persistence.MySQL.DaoFactory;
import java.awt.Frame;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.TableModelFacture;
import model.TableModelFactureImprimer;

import transfertObject.*;



public class JDFactureClient extends javax.swing.JDialog {

    /** Creates new form JDFacture */
    public JDFactureClient(Frame parent, String titre,Facture v) {
        super(parent,titre ,true);
        initComponents();
        fillComponents(v);
        ven=v;
       
        setLocation(parent.getX()+parent.getWidth()/4, parent.getY()+parent.getHeight()/8);
        setVisible(true);
       
    }
    
    public void fillComponents(Facture fact)
    {
        ArrayList <Client> cli = daoCli.selectClientNumCli(fact.getNumCli());
        ArrayList <FactureImprimer> listF = daoVen.selectFactureImprimer(fact.getNumFacture());
        float somTva = 0.0f , somPrix = 0.0f;
        
        jTextFieldNom.setText(cli.get(0).getTitre()+"  "+cli.get(0).getNomcli());
        jTextFieldPre.setText(cli.get(0).getPrenomcli());
        jTextFieldAdresse.setText(cli.get(0).getAdressecli()+"   "+cli.get(0).getCpcli()+" "+cli.get(0).getVillecli());
        jFTFDate.setText(fact.getDateBE());
        jTextFieldNum.setText(String.valueOf(fact.getNumFacture()));

         myModel.setMyList(daoVen.selectFactureImprimer(fact.getNumFacture()));
         
         for(FactureImprimer f:listF)
         {
             
         }
         jTextFieldNbMarch.setText(String.valueOf(listF.size()));
         jTextFieldMontva.setText(String.format("%.2f",fact.getPaye()));
         float r = fact.getPaye()- fact.getApayer();
         jTextFieldSomApay.setText(String.format("%.2f",r));
         
    }
    

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelFact = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabelNom = new javax.swing.JLabel();
        jLabelPre = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPre = new javax.swing.JTextField();
        jTextFieldAdresse = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFacture = new javax.swing.JTable (myModel);
        /* initialisation des largeurs de colonnes */
        javax.swing.table.TableColumn column = null;
        column = jTableFacture.getColumnModel().getColumn(0);
        column.setPreferredWidth(10);
        column = jTableFacture.getColumnModel().getColumn(1);
        column.setPreferredWidth(100);
        column = jTableFacture.getColumnModel().getColumn(2);
        column.setPreferredWidth(100);
        column = jTableFacture.getColumnModel().getColumn(3);
        column.setPreferredWidth(10);
        column = jTableFacture.getColumnModel().getColumn(4);
        column.setPreferredWidth(50);
        column = jTableFacture.getColumnModel().getColumn(5);
        column.setPreferredWidth(50);

        //jTableApp.setRowSorter(new TableRowSorter(myModel));
        jPanel3 = new javax.swing.JPanel();
        jLabelNb = new javax.swing.JLabel();
        jLabelTva = new javax.swing.JLabel();
        jLabelSom = new javax.swing.JLabel();
        jTextFieldNbMarch = new javax.swing.JTextField();
        jTextFieldMontva = new javax.swing.JTextField();
        jTextFieldSomApay = new javax.swing.JTextField();
        jTextFieldEncaisser = new javax.swing.JTextField();
        jButtonEncaisser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonQ = new javax.swing.JButton();
        jLabelDat = new javax.swing.JLabel();
        MaskFormatter mf = null;
        try{
            mf = new MaskFormatter("##/##/####");
        }catch(ParseException e)
        {
            System.out.println(e.getMessage());
        }
        jFTFDate = new JFormattedTextField(mf);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName(""); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabelFact.setFont(new java.awt.Font("Traditional Arabic", 1, 11)); // NOI18N
        jLabelFact.setForeground(new java.awt.Color(0, 0, 204));
        jLabelFact.setText("FACTURE    N° :");

        jTextFieldNum.setEditable(false);
        jTextFieldNum.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelNom.setFont(new java.awt.Font("Traditional Arabic", 1, 11)); // NOI18N
        jLabelNom.setForeground(new java.awt.Color(0, 51, 204));
        jLabelNom.setText("Nomcli :");

        jLabelPre.setFont(new java.awt.Font("Traditional Arabic", 1, 11)); // NOI18N
        jLabelPre.setForeground(new java.awt.Color(0, 0, 255));
        jLabelPre.setText("Prenomcli :");

        jLabelAdresse.setFont(new java.awt.Font("Traditional Arabic", 1, 11)); // NOI18N
        jLabelAdresse.setForeground(new java.awt.Color(0, 0, 204));
        jLabelAdresse.setText("Adressecli:");

        jTextFieldNom.setEditable(false);
        jTextFieldNom.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNom.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jTextFieldNom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldPre.setEditable(false);
        jTextFieldPre.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPre.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jTextFieldPre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldAdresse.setEditable(false);
        jTextFieldAdresse.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAdresse.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jTextFieldAdresse.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTableFacture.setModel(myModel);
        jScrollPane1.setViewportView(jTableFacture);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelNb.setFont(new java.awt.Font("Traditional Arabic", 1, 11)); // NOI18N
        jLabelNb.setForeground(new java.awt.Color(0, 0, 204));
        jLabelNb.setText("Nombre de Marchandises :");

        jLabelTva.setFont(new java.awt.Font("Traditional Arabic", 1, 11)); // NOI18N
        jLabelTva.setForeground(new java.awt.Color(0, 0, 204));
        jLabelTva.setText("Montant TVA :");

        jLabelSom.setFont(new java.awt.Font("Traditional Arabic", 1, 11)); // NOI18N
        jLabelSom.setForeground(new java.awt.Color(0, 0, 204));
        jLabelSom.setText("Montant à Payer :");

        jTextFieldNbMarch.setEditable(false);
        jTextFieldNbMarch.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldNbMarch.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldMontva.setEditable(false);
        jTextFieldMontva.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldMontva.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldSomApay.setEditable(false);
        jTextFieldSomApay.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldSomApay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldEncaisser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEncaisserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEncaisserKeyTyped(evt);
            }
        });

        jButtonEncaisser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonEncaisser.setForeground(new java.awt.Color(0, 0, 153));
        jButtonEncaisser.setText("Encaisser");
        jButtonEncaisser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEncaisserMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Montant");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSom, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMontva, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNbMarch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldSomApay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldEncaisser, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEncaisser))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldMontva, jTextFieldNbMarch, jTextFieldSomApay});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldNbMarch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelNb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMontva, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTva, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSomApay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEncaisser)
                    .addComponent(jTextFieldEncaisser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldMontva, jTextFieldNbMarch, jTextFieldSomApay});

        jButtonQ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/exit-32.png"))); // NOI18N
        jButtonQ.setText("Quitter");
        jButtonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQActionPerformed(evt);
            }
        });

        jLabelDat.setFont(new java.awt.Font("Traditional Arabic", 1, 11)); // NOI18N
        jLabelDat.setForeground(new java.awt.Color(0, 0, 204));
        jLabelDat.setText("Date :");

        jFTFDate.setEditable(false);
        jFTFDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAdresse)
                            .addComponent(jLabelNom)
                            .addComponent(jLabelFact, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabelPre)
                                        .addGap(30, 30, 30)
                                        .addComponent(jTextFieldPre, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addGap(313, 313, 313))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(340, 340, 340)
                                        .addComponent(jLabelDat)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFTFDate, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                        .addGap(32, 32, 32))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                .addGap(519, 519, 519)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFact)
                    .addComponent(jTextFieldNum)
                    .addComponent(jLabelDat)
                    .addComponent(jFTFDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom)
                    .addComponent(jTextFieldPre)
                    .addComponent(jLabelPre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdresse)
                    .addComponent(jTextFieldAdresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQActionPerformed
     dispose();
    }//GEN-LAST:event_jButtonQActionPerformed

    private void jButtonEncaisserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEncaisserMouseClicked
        float encaisserCli = 0;
        try{
            encaisserCli = Float.valueOf(jTextFieldEncaisser.getText());        
            
            if(jTextFieldEncaisser.getText().trim().length() == 0 || 
                    Float.valueOf(jTextFieldEncaisser.getText().trim()) <= 0){
               JOptionPane.showMessageDialog(null, " Veuillez indiquez un montant > 0");
            }else{
                ven.setApayer(encaisserCli);
                daoVen.MAJMontantFact(ven);
                jTextFieldEncaisser.setText("0");
                this.jTextFieldSomApay.setText(String.format("%.2f",(ven.getPaye()- ven.getApayer())));
                
                refreshModel();
                
            }
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, " Veuillez indiquez un montant > 0");
        }    
        
        
    }//GEN-LAST:event_jButtonEncaisserMouseClicked

    private void jTextFieldEncaisserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEncaisserKeyPressed
        
    }//GEN-LAST:event_jTextFieldEncaisserKeyPressed

    private void jTextFieldEncaisserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEncaisserKeyTyped
         
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
        //solution pour verifier que le 3characteres puisse etre tapez au clavier
        String car = String.valueOf(evt.getKeyChar());
        if ("-,.".contains(car)){
            jTextFieldEncaisser.setText(jTextFieldEncaisser.getText() + car);
        }           
        
    }//GEN-LAST:event_jTextFieldEncaisserKeyTyped

    private void refreshModel() {
      
        myModelFact.setMyList(daoVen.selectFacture());
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEncaisser;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JFormattedTextField jFTFDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelDat;
    private javax.swing.JLabel jLabelFact;
    private javax.swing.JLabel jLabelNb;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPre;
    private javax.swing.JLabel jLabelSom;
    private javax.swing.JLabel jLabelTva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFacture;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldEncaisser;
    private javax.swing.JTextField jTextFieldMontva;
    private javax.swing.JTextField jTextFieldNbMarch;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNum;
    private javax.swing.JTextField jTextFieldPre;
    private javax.swing.JTextField jTextFieldSomApay;
    // End of variables declaration//GEN-END:variables

    private IDaoClient daoCli = DaoFactory.getDaoClient();
    private IDaoCommande daoCmd = DaoFactory.getDaoCommande();
    private IDaoFacture daoVen = DaoFactory.getDaoFacture();
    private IDaoProduit daoprod = DaoFactory.getDAOProduit();
    private TableModelFactureImprimer myModel = new model.TableModelFactureImprimer(daoVen.selectFacture()) ;
    private TableModelFacture myModelFact = new model.TableModelFacture(daoVen.selectFacture());
    float prix, tva,prixApayer;
    Facture ven;
}
