/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;


import persistence.IDaofournisseur;
import persistence.MySQL.DaoFactory;
import java.awt.Dialog;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.TableModelFournisseur;

import transfertObject.Fournisseur;



public class JDRechercheFournisseur extends javax.swing.JDialog {
    JInternalFrame parent;
    /**
     * Creates new form JDRechercheProduit
     */
    
     public JDRechercheFournisseur(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
     
    }
    

     public JDRechercheFournisseur(Dialog Parent,String titre,Fournisseur four)
     {
         super(Parent, titre, true);
        initComponents();
        fillComponents();
        setLocationByPlatform(true);
        setLocation(Parent.getX()+Parent.getWidth()/3, Parent.getY()+Parent.getHeight()/3);
        fournisseur =four;
        
         
        setVisible(true);
     }
    

    JDRechercheFournisseur(JInternalFrame parent, String recherche, Fournisseur four) {
        
        this.parent=parent;
        
         initComponents();
        fillComponents();
         fournisseur =four;
         setLocation(parent.getX()+parent.getWidth()/3, parent.getY()+parent.getHeight()/8);
        setLocationByPlatform(true);
        this.setVisible(true); 

        
    }
    
     private void fillComponents()
    {
        /* charger toutes les catégories */
      
        ArrayList <Fournisseur> fourr = daoF.selectFournisseur();
       
        int i;
        for ( i=0;i<fourr.size();i++)
        {  for(int j=i+1;j<fourr.size();j++)              
            { 
            if(fourr.get(i).getSociete().compareTo(fourr.get(j).getSociete())==0)
                {
                                                                                      
                    fourr.remove(i);// supprimé l'element dans la table                       
                        }
                                    
                   }
        }
        jComboBoxSoc.removeAllItems();
        jComboBoxSoc.addItem("<tous>");
        for( i=0;i<fourr.size();i++) 
        {
           jComboBoxSoc.addItem(((Fournisseur)fourr.get(i)).getSociete());
        }      
    
        

     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAjouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSoc = new javax.swing.JComboBox();
        jButtonOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFour = new javax.swing.JTable(myModel);
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("recherche fournisseur");

        jButtonAjouter.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAjouter.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButtonAjouter.setForeground(new java.awt.Color(0, 0, 204));
        jButtonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajout.jpg"))); // NOI18N
        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonModifier.setBackground(new java.awt.Color(204, 255, 204));
        jButtonModifier.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButtonModifier.setForeground(new java.awt.Color(0, 0, 204));
        jButtonModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modif.jpg"))); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Filter.png"))); // NOI18N
        jLabel1.setText("recherche par société:");

        jComboBoxSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSocActionPerformed(evt);
            }
        });

        jButtonOK.setBackground(new java.awt.Color(153, 255, 204));
        jButtonOK.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKMouseClicked(evt);
            }
        });
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jTableFour.setModel(myModel);
        jTableFour.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableFour.setShowHorizontalLines(false);
        jTableFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFourMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFour);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxSoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButtonAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModifier)
                .addGap(47, 47, 47)
                .addComponent(jButtonOK))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonModifier)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOK))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        
         JDialog parent = new JDialog();
             new JDFournisseur(parent, "INSERTION DU FOURNISEUR");
     
        refreshModel();
        
         fillComponents();

    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
     
        if (jTableFour.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null,"Sélectionnez d'abord une ligne svp !","Gestion Pharm",JOptionPane.ERROR_MESSAGE);
        else {
            Fournisseur four = myModel.getMyList(jTableFour.getSelectedRow());

            new JDFournisseur(this, "MODIFICATION FOURNISSEUR",four  );

            refreshModel();
            fillComponents();
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jTableFourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFourMouseClicked
         fournisseur = myModel.getMyList(jTableFour.getSelectedRow());
                if (evt.getClickCount() >= 2){
                    //verifier si c'est variable parent est dans la JIFComm
                    if (parent instanceof JIFCommande){
                        ((JIFCommande)parent).setFour(fournisseur);
                    }
                    else {
                        ((JIFLivrer)parent).setFour(fournisseur);
                        
                    }
                    
                    dispose();
                }    
    }//GEN-LAST:event_jTableFourMouseClicked

    private void jComboBoxSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSocActionPerformed
         refreshModel();
    }//GEN-LAST:event_jComboBoxSocActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
         if (jTableFour.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null,"Sélectionnez d'abord une ligne svp !","Gestion Pharm",JOptionPane.ERROR_MESSAGE);
        else {
        fournisseur = myModel.getMyList(jTableFour.getSelectedRow());
         if (parent instanceof JIFCommande){
                        ((JIFCommande)parent).setFour(fournisseur);
                    }
                    else {
                        ((JIFLivrer)parent).setFour(fournisseur);
                        
                    }
                    
               dispose();
         } 
                   
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKMouseClicked
        fournisseur = myModel.getMyList(jTableFour.getSelectedRow());
                  ((JIFCommande)parent).setFour(fournisseur);
                    dispose();
    }//GEN-LAST:event_jButtonOKMouseClicked
       
    
    private void refreshModel() {
       String societe = (String)jComboBoxSoc.getSelectedItem();
       
       if (societe != null ) // obligatoire car sinon provoque une erreur au remplissage de jComboBox,
                                        
        {
            if (societe.equals("<tous>")) {
                societe = "%";
            }
            
        myModel.setMyList(daoF.selectFournisseur());
        myModel.setMyList(daoF.selectFournisseurSoc(societe));
        }
        
        
         
    
        } 
         
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDRechercheFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDRechercheFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDRechercheFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDRechercheFournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDRechercheFournisseur dialog = new JDRechercheFournisseur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxSoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFour;
    // End of variables declaration//GEN-END:variables

     private IDaofournisseur daoF = DaoFactory.getDaofournisseur();
    private TableModelFournisseur myModel = new TableModelFournisseur(daoF.selectFournisseur());
    ArrayList <Fournisseur> myList = daoF.selectFournisseur();
    Fournisseur fournisseur;
      static boolean modif = false;
}
