 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import persistence.IDaoLigneVente;
import persistence.IDaoProduit;
import persistence.MySQL.DaoFactory;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import model.TableModelLigneVente;
import model.TableModelProduit;
import transfertObject.Produit;



public class JDRechercheProduit extends javax.swing.JDialog {

    /**
     * Creates new form JDRechercheProduit
     */
    public JDRechercheProduit(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
     public JDRechercheProduit(final JDLigneVente parentrech,String titre,Produit prod)
     {
         super(parentrech, titre, true);
          initComponents();
          //on rajout dans le combo ceux valeur
        motKey.add("Tous");
        motKey.add("Designation");
        motKey.add("Delivrance");
        
        
        this.parentrech = parentrech;
        
     for (String s : motKey)
            jComboBoxPro.addItem(s.toString());
     
     setLocationByPlatform(true);//centré le jdialog
     
      jTablePro.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                if (e.getClickCount() >= 2){
                    produit = myModelPro.getMyList(jTablePro.getSelectedRow());

                   ((JDLigneVente)parentrech).setProduct(produit);
                dispose();
                }
            }
        });   
            jToggleButton1.setVisible(false);
           setVisible(true);
          
     }

     public JDRechercheProduit( final JInternalFrame parent,String titre,Produit prod)
     {
         
        initComponents();
        
        motKey.add("Tous");
        motKey.add("Designation");
        motKey.add("Delivrance");
        this.parent = parent;
     for (String s : motKey)
            
            jComboBoxPro.addItem(s.toString());
     
     setLocationByPlatform(true);//centré le jdialog
      jTablePro.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                if (e.getClickCount() >= 2){
                    produit = myModelPro.getMyList(jTablePro.getSelectedRow());
                    if (parent instanceof JIFCommande){
                        ((JIFCommande)parent).setProduct(produit);
                    }else{
                        ((JIFLivrer)parent).setProduct(produit);
                    }
                     
          
                dispose();
                }
            }
        });   
        
        
        setVisible(true);
     }

     
                
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldRech = new javax.swing.JTextField();
        jButtonrech = new javax.swing.JButton();
        jComboBoxPro = new javax.swing.JComboBox();
        jButtonOK = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePro = 
        new javax.swing.JTable(myModelPro);
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("recherche produit");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Filter.png"))); // NOI18N
        jLabel1.setText("Recherche Produit par:");

        jTextFieldRech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRechKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRechKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRechKeyTyped(evt);
            }
        });

        jButtonrech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-icon.png"))); // NOI18N
        jButtonrech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonrechMouseClicked(evt);
            }
        });

        jButtonOK.setBackground(new java.awt.Color(153, 255, 204));
        jButtonOK.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonOK.setText("Ok");
        jButtonOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOKMouseClicked(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jToggleButton1.setText("à commander");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jTablePro.setModel(myModelPro);
        jTablePro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablePro.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jTablePro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRech, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonrech)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonrech, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldRech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1))
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechKeyReleased
       
    }//GEN-LAST:event_jTextFieldRechKeyReleased

    private void jButtonrechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonrechMouseClicked
        //faire une recherche avec un critere le mot clé de la zone de texte.
         //rechercher le composant sur lequel on a eu evenement
        //si  0=tous,si 1=designation,si 2=delivrance
        //rafraichir la list .
        if(jTextFieldRech.getText().isEmpty()){
            myModelPro.setMyList(daoprod.selectProduit());
           // JOptionPane.showMessageDialog(null,"svp veuillez indiquer votre choix à la liste deroulante!et à la zone texte","Gestion Pharm",JOptionPane.INFORMATION_MESSAGE);
            
        }else{
               
         String f = (String) jComboBoxPro.getSelectedItem();
      
        String keyWord = jTextFieldRech.getText();
        if (f.equals(motKey.toArray()[0])){
            myModelPro.setMyList(daoprod.selectProduit());
        }
        if (f.equals(motKey.toArray()[1])){
             myModelPro.setMyList(daoprod.ProduitParDesignation(keyWord));
        }else if (f.equals(motKey.toArray()[2])){
             myModelPro.setMyList(daoprod.ProduitParDelivrance(keyWord));
        }
        myModelPro.refresh();
        
        
        }
    }//GEN-LAST:event_jButtonrechMouseClicked

    private void jTextFieldRechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechKeyTyped
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())){
            evt.consume();
        }
                          
    }//GEN-LAST:event_jTextFieldRechKeyTyped

    private void jButtonOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOKMouseClicked
          if (jTablePro.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null,"Sélectionnez d'abord une ligne svp !","Gestion Pharm",JOptionPane.ERROR_MESSAGE);
        else {  
        produit = myModelPro.getMyList(jTablePro.getSelectedRow());
          if (parent instanceof JIFCommande){
                        ((JIFCommande)parent).setProduct(produit);
              
                      
                    }
          else if (parent instanceof JIFLivrer){
                        ((JIFLivrer)parent).setProduct(produit);
                    }
          else if (parentrech instanceof JDLigneVente) {
                        ((JDLigneVente)parentrech).setProduct(produit);
                     
                    }
          
          
        dispose();
          }
                
    }//GEN-LAST:event_jButtonOKMouseClicked

    private void jTextFieldRechKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechKeyPressed
        
               
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
         String f = (String) jComboBoxPro.getSelectedItem();
        
        String keyWord = jTextFieldRech.getText();
        
        if (f.equals(motKey.toArray()[0])){
            myModelPro.setMyList(daoprod.selectProduit());
        }
         if (f.equals(motKey.toArray()[1])){
             myModelPro.setMyList(daoprod.ProduitParDesignation(keyWord));
        }else if (f.equals(motKey.toArray()[2])){
             myModelPro.setMyList(daoprod.ProduitParDelivrance(keyWord));
        }
        
        myModelPro.refresh();
        
        
        }
            
       
           
    }//GEN-LAST:event_jTextFieldRechKeyPressed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
       
       if (((JToggleButton)evt.getSource()).isSelected()){
           myModelPro.setMyList(daoprod.selectProduitCompareStockQuantite());
       }
       else {
           myModelPro.setMyList(myList);
       }
    }//GEN-LAST:event_jToggleButton1MouseClicked
    
     
     
       private void refreshModel() {
       
        myModelLv.setMyList(daoLv.selectLigneVente());
        myModelPro.setMyList(daoprod.selectProduit());
        
           
    }
    
    /**
     * @param args the command linelLv.setMyList(daoLv.selectLigneVenteParCodepro(prod.getCode_prod()));
          myModel.setMyList(daoLv.selectLigneVenteParCodepro(pr.getCode_prod())); arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDRechercheProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDRechercheProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDRechercheProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDRechercheProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDRechercheProduit dialog = new JDRechercheProduit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonrech;
    private javax.swing.JComboBox jComboBoxPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePro;
    private javax.swing.JTextField jTextFieldRech;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

     private IDaoProduit daoprod = DaoFactory.getDAOProduit();
     private IDaoLigneVente daoLv=DaoFactory.getDaoLigneVente();
    private TableModelProduit myModelPro = new TableModelProduit(daoprod.selectProduit());
    private TableModelLigneVente myModelLv=new model.TableModelLigneVente(daoLv.selectLigneVente());
    ArrayList <Produit> myList = daoprod.selectProduit();
    public ArrayList<String> motKey = new ArrayList<String>();
    Produit produit; 
    JInternalFrame parent;
    JDialog parentrech;
    
}
