/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import transfertObject.Utilisateur;

public class JFPrincipale extends javax.swing.JFrame {
    
    String titre;

    /**
     * Creates new form JFPrincipale
     */
    public JFPrincipale()  {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        titre = "Gestion Pharm";
         // afficher le jifLogin dans la jDesktopane
         JIFLogin jiflogin = new JIFLogin(this);
         jDesktopPane1.add(jiflogin);
        try {
            jiflogin.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);
        }
         jiflogin.setVisible(true);
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jMenuItemDeconnexion = new javax.swing.JMenuItem();
        jMenuItemQuitter = new javax.swing.JMenuItem();
        jMenuListeChoix = new javax.swing.JMenu();
        jMenuItemVente2 = new javax.swing.JMenuItem();
        jMenuItemCmd2 = new javax.swing.JMenuItem();
        jMenuItemLivrer = new javax.swing.JMenuItem();
        jMenuItemProduit = new javax.swing.JMenuItem();
        jMenuItemUtil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion pharm");
        setLocationByPlatform(true);
        setName("page d'accueil"); // NOI18N

        jDesktopPane1.setForeground(new java.awt.Color(51, 51, 51));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pharma.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(1188, 587, 1188, 587);

        jMenuFichier.setForeground(new java.awt.Color(0, 0, 204));
        jMenuFichier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/My-computer-Windows-8-32.png"))); // NOI18N
        jMenuFichier.setText("FICHIER");
        jMenuFichier.setEnabled(false);
        jMenuFichier.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N

        jMenuItemDeconnexion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemDeconnexion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemDeconnexion.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItemDeconnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/quitter.png"))); // NOI18N
        jMenuItemDeconnexion.setText("Deconnexion");
        jMenuItemDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeconnexionActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemDeconnexion);

        jMenuItemQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemQuitter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemQuitter.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItemQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/exit-32.png"))); // NOI18N
        jMenuItemQuitter.setText("Quiiter");
        jMenuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitterActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemQuitter);

        jMenuBar1.add(jMenuFichier);

        jMenuListeChoix.setForeground(new java.awt.Color(0, 0, 204));
        jMenuListeChoix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Refresh.png"))); // NOI18N
        jMenuListeChoix.setText("LISTE CHOIX");
        jMenuListeChoix.setEnabled(false);
        jMenuListeChoix.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jMenuListeChoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListeChoixActionPerformed(evt);
            }
        });

        jMenuItemVente2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVente2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemVente2.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemVente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Shopping-Cart-payment-32.png"))); // NOI18N
        jMenuItemVente2.setText("Ventes");
        jMenuItemVente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVente2ActionPerformed(evt);
            }
        });
        jMenuListeChoix.add(jMenuItemVente2);

        jMenuItemCmd2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCmd2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemCmd2.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemCmd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Goods-32_1.png"))); // NOI18N
        jMenuItemCmd2.setText("Commandes");
        jMenuItemCmd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCmd2ActionPerformed(evt);
            }
        });
        jMenuListeChoix.add(jMenuItemCmd2);

        jMenuItemLivrer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemLivrer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemLivrer.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemLivrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Application_de_devis_facture_icone.png"))); // NOI18N
        jMenuItemLivrer.setText("Livraison");
        jMenuItemLivrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLivrerActionPerformed(evt);
            }
        });
        jMenuListeChoix.add(jMenuItemLivrer);

        jMenuItemProduit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemProduit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemProduit.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Cashbox-32.png"))); // NOI18N
        jMenuItemProduit.setText("Produit");
        jMenuItemProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProduitActionPerformed(evt);
            }
        });
        jMenuListeChoix.add(jMenuItemProduit);

        jMenuItemUtil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemUtil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItemUtil.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemUtil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dossier-utilisateur-icone-5253-32.png"))); // NOI18N
        jMenuItemUtil.setText("Utilisateur");
        jMenuItemUtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUtilActionPerformed(evt);
            }
        });
        jMenuListeChoix.add(jMenuItemUtil);

        jMenuBar1.add(jMenuListeChoix);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    //methode pour qui passe en parametre un utilisateur 
    //pour pouvoir   afficher en premier la fenetre vente 
    
    public void t(Utilisateur ut){
        this.utilisateur = ut;
        this.setTitle(titre + " - " + ut.getNomId());
        jDesktopPane1.removeAll();
        JIFVente g = new JIFVente(ut);
        jDesktopPane1.add(g);
        try {
            g.setVisible(true);
            g.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.repaint();
    }
    
    private void jMenuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitterActionPerformed

        int rep = JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment quitter l'application ?","Gestion Pharm",JOptionPane.YES_NO_OPTION);
        if (rep == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemQuitterActionPerformed

    private void jMenuItemUtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUtilActionPerformed
        
        jDesktopPane1.removeAll();
        JIFUtilisateur u = new JIFUtilisateur();
        jDesktopPane1.add(u);
        try {
            u.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);
        }


    jDesktopPane1.repaint();
                    
    }//GEN-LAST:event_jMenuItemUtilActionPerformed

    private void jMenuItemDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeconnexionActionPerformed
           
        int rep = JOptionPane.showConfirmDialog(null,"Voulez-vous vous deconnectez  ?","Gestion Pharm",JOptionPane.YES_NO_OPTION);
        
        if (rep == JOptionPane.YES_OPTION){
          jDesktopPane1.removeAll();
          JIFLogin jiflogin = new JIFLogin(this);
          jDesktopPane1.add(jiflogin);
          jMenuFichier.setEnabled(false);
          jMenuListeChoix.setEnabled(false);
          
          try {
              jiflogin.setMaximum(true);
              jiflogin.setVisible(true);
          } catch (PropertyVetoException ex) {
              Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);
          }
          this.setTitle(titre);
          jDesktopPane1.repaint();
         
      }
    }//GEN-LAST:event_jMenuItemDeconnexionActionPerformed

    private void jMenuListeChoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListeChoixActionPerformed
      
    }//GEN-LAST:event_jMenuListeChoixActionPerformed

    private void jMenuItemVente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVente2ActionPerformed
        jDesktopPane1.removeAll();
        
        JIFVente ven2 = new JIFVente(utilisateur);
          jDesktopPane1.add(ven2);
           try {
            ven2.setMaximum(true);
            ven2.setVisible(true);
         } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);

      jDesktopPane1.repaint();
        
        }                          
    }//GEN-LAST:event_jMenuItemVente2ActionPerformed
 
    private void jMenuItemCmd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCmd2ActionPerformed
        jDesktopPane1.removeAll();
        
        JIFCommande Cmd2 = new JIFCommande();
          jDesktopPane1.add(Cmd2);
           try {
            Cmd2.setMaximum(true);
            Cmd2.setVisible(true);
         } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);

      jDesktopPane1.repaint();
    }                         
    }//GEN-LAST:event_jMenuItemCmd2ActionPerformed

    private void jMenuItemLivrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLivrerActionPerformed
             
        jDesktopPane1.removeAll();
        JIFLivrer liv = new JIFLivrer();
        jDesktopPane1.add(liv);
        try{
            liv.setMaximum(true);
            liv.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);

      jDesktopPane1.repaint();
    }     
    }//GEN-LAST:event_jMenuItemLivrerActionPerformed

    private void jMenuItemProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProduitActionPerformed
                
        jDesktopPane1.removeAll();
       JIFProduit jiproduit = new JIFProduit();
        jDesktopPane1.add(jiproduit);
        try{
            jiproduit.setMaximum(true);
            jiproduit.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipale.class.getName()).log(Level.SEVERE, null, ex);

      jDesktopPane1.repaint();
    } 
    }//GEN-LAST:event_jMenuItemProduitActionPerformed
 
    
    // }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
               ((JFPrincipale)new JFPrincipale()).setVisible(true);
                 
            }
        });
        
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenuItem jMenuItemCmd2;
    private javax.swing.JMenuItem jMenuItemDeconnexion;
    private javax.swing.JMenuItem jMenuItemLivrer;
    public javax.swing.JMenuItem jMenuItemProduit;
    private javax.swing.JMenuItem jMenuItemQuitter;
    public javax.swing.JMenuItem jMenuItemUtil;
    private javax.swing.JMenuItem jMenuItemVente2;
    public javax.swing.JMenu jMenuListeChoix;
    // End of variables declaration//GEN-END:variables

    private Utilisateur utilisateur = null;
}
