/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import persistence.IDaoLigneCommande;
import persistence.IDaoProduit;
import persistence.MySQL.DaoFactory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.TableModelLivrer;
import model.TableModelProduit;
import transfertObject.Commande;
import transfertObject.Fournisseur;
import transfertObject.LigneCommande;
import transfertObject.Livrer;
import transfertObject.Produit;


public class JIFLivrer extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFLivraison
     */
    public JIFLivrer() {
        initComponents();
        cmd = new Commande();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivrer = new javax.swing.JTable();
        jButtonFr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFournisseur = new javax.swing.JTextField();
        jButtonRechProduit = new javax.swing.JButton();
        jTextFieldProduit = new javax.swing.JTextField();
        jTextFQteLivrer = new javax.swing.JTextField();
        jButtonOk1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("livraisons");

        jTableLivrer.setModel(myModelLivrer
        );
        jScrollPane1.setViewportView(jTableLivrer);

        jButtonFr.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonFr.setForeground(new java.awt.Color(0, 102, 102));
        jButtonFr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-icon.png"))); // NOI18N
        jButtonFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Fournisseur");

        jTextFieldFournisseur.setEditable(false);
        jTextFieldFournisseur.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFournisseurActionPerformed(evt);
            }
        });

        jButtonRechProduit.setForeground(new java.awt.Color(0, 0, 255));
        jButtonRechProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-icon.png"))); // NOI18N
        jButtonRechProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechProduitActionPerformed(evt);
            }
        });

        jTextFieldProduit.setEditable(false);
        jTextFieldProduit.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldProduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldProduitKeyReleased(evt);
            }
        });

        jTextFQteLivrer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFQteLivrerKeyTyped(evt);
            }
        });

        jButtonOk1.setBackground(new java.awt.Color(204, 255, 204));
        jButtonOk1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonOk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/ajouter.png"))); // NOI18N
        jButtonOk1.setText("OK");
        jButtonOk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOk1MouseClicked(evt);
            }
        });
        jButtonOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOk1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Produit");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Quantité");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonFr, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRechProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFQteLivrer, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(jButtonOk1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFQteLivrer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jButtonRechProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextFieldProduit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFournisseur)))
                    .addComponent(jButtonOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonFr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrActionPerformed
        new JDRechercheFournisseur(this, "recherche",four);
     
    }//GEN-LAST:event_jButtonFrActionPerformed

    private void jButtonRechProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechProduitActionPerformed


        new JDRechercheProduit(this, "ECRAN  pro",produit);
        myModelPro.refresh();

    }//GEN-LAST:event_jButtonRechProduitActionPerformed

    private void jTextFieldProduitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProduitKeyReleased

    }//GEN-LAST:event_jTextFieldProduitKeyReleased

    private void jTextFQteLivrerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFQteLivrerKeyTyped
        if(! Character.isDigit(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_jTextFQteLivrerKeyTyped

    private void jButtonOk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOk1MouseClicked
        //rempli la jtableLivrer dans le JIFLivrer
        if(jTextFieldProduit.getText().equals("")||jTextFQteLivrer.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir les champs.", "Gestion Pharm", JOptionPane.INFORMATION_MESSAGE);
        }        
        
        Fournisseur fourn = this.getFournisseur();
        
        Livrer livrer = new Livrer();
        livrer.setProduit(produit);
        livrer.setQuantite_livrer(Integer.valueOf(jTextFQteLivrer.getText()));
        
        ArrayList <LigneCommande> lignecommandes = daoLgc.selectLignComParnumfCodP(fourn, livrer);
        
        daoLgc.selectSumQteParCdPro(fourn, livrer);        
        
        System.out.println("Tableau initiale");
        for (LigneCommande l : lignecommandes){
            System.out.println(l.getCode_Prod() + " " + l.getNumFour() + " qtecmd " + l.getQuantite_renouvele()+
                    " qtelivrer " +l.getQuantite_livrer()+ " qterestant " +l.getQuantite_restant());
        }
        System.out.println("Quantité d'unité en attente de livraison : " + livrer.getQuantite_restant() + "\n");
        
        System.out.println("Tableau initiale rectifie");
        int qtelivrer = livrer.getQuantite_livrer();
        int restlivrer = 0;
        for(LigneCommande l: lignecommandes){
            if (l.getQuantite_restant() < qtelivrer){
                restlivrer = l.getQuantite_restant();
                l.setQuantite_livrer(l.getQuantite_restant() + l.getQuantite_livrer());
                l.setQuantite_restant(0);
                
            } else if (l.getQuantite_restant() > qtelivrer ) {
                restlivrer = qtelivrer;
                l.setQuantite_livrer(l.getQuantite_livrer() + qtelivrer) ;
                l.setQuantite_restant(l.getQuantite_restant() - qtelivrer);
                                
            } else if (l.getQuantite_restant() == qtelivrer ){ 
                restlivrer = qtelivrer;
                l.setQuantite_livrer(qtelivrer) ;
                l.setQuantite_restant(0) ;
            }
            qtelivrer -= restlivrer;
            
            System.out.println(l.getCode_Prod() + " " + l.getNumFour() + " qtecmd " + l.getQuantite_renouvele()+
                    " qtelivrer " +l.getQuantite_livrer()+ " qterestant " +l.getQuantite_restant());

            if (0 == qtelivrer ){
                break;
            }
        }
        System.out.println("Rectification terminée\n");
        
       // System.out.println(livrer.getQuantite_restant());
        AjoutProduitLivrer(livrer);
        
        daoLgc.updateLigncom(lignecommandes);
        
        produit.setStock(produit.getStock () + Integer.valueOf(jTextFQteLivrer.getText()));
        daoprod.updatestockProduit(produit);
        
        jTextFQteLivrer.setText("");
        jTextFieldProduit.setText("");
    }//GEN-LAST:event_jButtonOk1MouseClicked

    private void jButtonOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOk1ActionPerformed

    private void jTextFieldFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFournisseurActionPerformed
    
    
    public  void setFour(Fournisseur fournisseur) {
       
        cmd.setFournisseur(fournisseur);
        jTextFieldFournisseur.setText(fournisseur.getNomFr());  
        this.four=fournisseur;
      
    }
    public Fournisseur getFournisseur(){
        return four;
    }
   
    public void AjoutProduitLivrer(Livrer livrer){
        daoLgc.selectSumQteParCdPro(four, livrer);
       
        myModelLivrer.setMyList(livrer);
        
        
        
    }
    
     public void setProduct(Produit produit){
        this.produit = produit;
        jTextFieldProduit.setText(produit.getDesignation());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFr;
    private javax.swing.JButton jButtonOk1;
    private javax.swing.JButton jButtonRechProduit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivrer;
    private javax.swing.JTextField jTextFQteLivrer;
    private javax.swing.JTextField jTextFieldFournisseur;
    private javax.swing.JTextField jTextFieldProduit;
    // End of variables declaration//GEN-END:variables

   private  Fournisseur four;
    private Commande cmd;
    private IDaoLigneCommande daoLgc = DaoFactory.getDaoLigneCommande();
    private TableModelLivrer myModelLivrer = new model.TableModelLivrer();
   
    private IDaoProduit daoprod = DaoFactory.getDAOProduit();
   
    private TableModelProduit myModelPro = new model.TableModelProduit();
    private Produit produit;
    JIFLivrer parent;
    
}
