/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import util.cryptingUtil;
import persistence.MySQL.ConnexionLogin;
import persistence.MySQL.DaoFactory;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.TableModelUtilisateur;
import persistence.MySQL.DaoUtilisateurImpl;
import transfertObject.Utilisateur;
import transfertObject.Utilisateur.TypeUtilisateur;


public class JIFLogin extends javax.swing.JInternalFrame {
    //declaration
    ResultSet rs;
    ConnexionLogin db;
    String username1,password1,typ;
    JFrame parent;
    JFPrincipale jfprincipale;
    /**
     * Creates new form JIFLogin
     */
    public JIFLogin(JFrame parent) {
        initComponents();
        db = new ConnexionLogin();
        this.parent = parent;
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Indentification");
        setDoubleBuffered(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 2147483647));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Nom d'utilisateur:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 110, 22));

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usernameKeyTyped(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 270, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Mot de passe:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passwordKeyTyped(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 270, 30));

        jButtonLogin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/valider.png"))); // NOI18N
        jButtonLogin.setText("Valider");
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pharma/Coupe_d'Hygie.svg.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 280));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 25;
        gridBagConstraints.ipadx = 520;
        gridBagConstraints.ipady = 180;
        getContentPane().add(jPanel1, gridBagConstraints);

        setBounds(0, 0, 959, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed

        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.connect();
            
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void jButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseClicked
        this.connect();
        
        
    }//GEN-LAST:event_jButtonLoginMouseClicked

    private void txt_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyTyped
        if(!Character.isLetter(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txt_usernameKeyTyped

    private void txt_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyTyped
       
    }//GEN-LAST:event_txt_passwordKeyTyped
   
    private void connect(){
        if(txt_username.getText().trim().isEmpty() || txt_password.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Le nom de l'utilisateur ou le mot de passe est incorrect.");
        }
        else {
            try {
                Utilisateur utilisateur = daoUtil.getUtilisateurPasswordByUserNameAndPassword(txt_username.getText(), cryptingUtil.encryptPassword(txt_password.getText()));
                System.out.println("user type : = " + utilisateur.getType());
                ((JFPrincipale)parent).t(utilisateur);
                
                boolean isGerant = utilisateur.getType().equals(TypeUtilisateur.Gerant);
                
                ((JFPrincipale)parent).jMenuItemUtil.setVisible(isGerant);
                ((JFPrincipale)parent).jMenuItemProduit.setVisible(isGerant);   
                                
                ((JFPrincipale)parent).jMenuFichier.setEnabled(true);    
                ((JFPrincipale)parent).jMenuListeChoix.setEnabled(true);
                
                refreshModel();
                
                
            } catch (NoSuchAlgorithmException | UnsupportedEncodingException ex) {
                JOptionPane.showMessageDialog(this,"Le nom de l'utilisateur ou le mot de passe est inconnu.");
                //Logger.getLogger(JIFLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Le nom de l'utilisateur ou le mot de passe est inconnu.");
                //Logger.getLogger(JIFLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }

    private void refreshModel() {
        myModel.setMyList(daoUtil.selectUtilisateur());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private final DaoUtilisateurImpl daoUtil = (DaoUtilisateurImpl) DaoFactory.getDaoUtilisateur();
    private final TableModelUtilisateur myModel = new model.TableModelUtilisateur (daoUtil.selectUtilisateur());

}
