/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import persistence.IDaoClient;
import persistence.IDaoLigneVente;
import persistence.IDaoFacture;
import persistence.MySQL.DaoFactory;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.TableModelClients;
import model.TableModelLigneVente;
import model.TableModelFacture;
import transfertObject.Client;
import transfertObject.LigneVente;
import transfertObject.Produit;
import transfertObject.Utilisateur;
import transfertObject.Facture;



public class JIFVente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFNouveauVente
     */
    public JIFVente(Utilisateur ut) {
        initComponents();
        util=ut;
        
         jTableFact.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                if (e.getClickCount() >= 2){
                    Facture v = myModel.getMyList(jTableFact.getSelectedRow());
                    JFrame parent = (JFrame)(JIFVente.super.getDesktopPane().getTopLevelAncestor());
                    new JDFactureClient(parent,"FICHE FACTURE DU CLIENT",v);
                }
            }
        });
        
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCli = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClients = new javax.swing.JTable (miModel);
        jButtonAjouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxRech = new javax.swing.JComboBox();
        jComboBoxFiltre = new javax.swing.JComboBox();
        jPanelVen = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCreerFacture = new javax.swing.JButton();
        jButtonClotureFacture = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableFact = new javax.swing.JTable (myModel);
        /* initialisation des largeurs de colonnes */
        // javax.swing.table.TableColumn column1 = null;
        //column1 = jTableFact.getColumnModel().getColumn(0);
        //column1.setPreferredWidth(10);
        //column1 = jTableFact.getColumnModel().getColumn(1);
        //column1.setPreferredWidth(25);
        //column1 = jTableFact.getColumnModel().getColumn(2);
        //column1.setPreferredWidth(55);
        //column1 = jTableFact.getColumnModel().getColumn(3);
        //column1.setPreferredWidth(50);
        //column1 = jTableFact.getColumnModel().getColumn(4);
        //column1.setPreferredWidth(55);
        //column1 = jTableFact.getColumnModel().getColumn(5);
        //column1.setPreferredWidth(55);
        //jTableApp.setRowSorter(new TableRowSorter(myModel));

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLV = new javax.swing.JTable();
        jButtonAjoutLigneVente = new javax.swing.JButton();
        jButtonSupprimerLignevent = new javax.swing.JButton();

        setTitle("Ventes");

        jTableClients.setModel(miModel);
        jTableClients.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClients);

        jButtonAjouter.setBackground(new java.awt.Color(204, 255, 255));
        jButtonAjouter.setFont(new java.awt.Font("Traditional Arabic", 3, 12)); // NOI18N
        jButtonAjouter.setForeground(new java.awt.Color(0, 0, 204));
        jButtonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajout.jpg"))); // NOI18N
        jButtonAjouter.setText("Ajouter client");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonModifier.setBackground(new java.awt.Color(204, 255, 255));
        jButtonModifier.setFont(new java.awt.Font("Traditional Arabic", 3, 12)); // NOI18N
        jButtonModifier.setForeground(new java.awt.Color(0, 0, 204));
        jButtonModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modif.jpg"))); // NOI18N
        jButtonModifier.setText("Modifier client");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonSupprimer.setBackground(new java.awt.Color(204, 255, 255));
        jButtonSupprimer.setFont(new java.awt.Font("Traditional Arabic", 3, 12)); // NOI18N
        jButtonSupprimer.setForeground(new java.awt.Color(0, 0, 204));
        jButtonSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprim.png"))); // NOI18N
        jButtonSupprimer.setText("Supprimer client");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Filter.png"))); // NOI18N
        jLabel2.setText("Rechercher client ");

        jComboBoxRech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Tous>", "Nom", "Code Postal", "Ville", " " }));
        jComboBoxRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRechActionPerformed(evt);
            }
        });

        jComboBoxFiltre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Tous>", "Monsieur", "Madame", "Mademoiselle" }));
        jComboBoxFiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCliLayout = new javax.swing.GroupLayout(jPanelCli);
        jPanelCli.setLayout(jPanelCliLayout);
        jPanelCliLayout.setHorizontalGroup(
            jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxRech, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(jButtonAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSupprimer)
                .addContainerGap())
            .addGroup(jPanelCliLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1)
                .addGap(12, 12, 12))
        );
        jPanelCliLayout.setVerticalGroup(
            jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelCliLayout.createSequentialGroup()
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCliLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCliLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxRech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCliLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)))
                .addGap(372, 372, 372))
        );

        jPanelCliLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAjouter, jButtonModifier, jButtonSupprimer});

        getContentPane().add(jPanelCli, java.awt.BorderLayout.PAGE_START);

        jPanelVen.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setOpaque(false);

        jButtonCreerFacture.setBackground(new java.awt.Color(204, 255, 204));
        jButtonCreerFacture.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jButtonCreerFacture.setForeground(new java.awt.Color(51, 51, 0));
        jButtonCreerFacture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Add.png"))); // NOI18N
        jButtonCreerFacture.setText("AjouterFacture");
        jButtonCreerFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerFactureActionPerformed(evt);
            }
        });

        jButtonClotureFacture.setBackground(new java.awt.Color(153, 255, 204));
        jButtonClotureFacture.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jButtonClotureFacture.setText("cloturefacture");
        jButtonClotureFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClotureFactureActionPerformed(evt);
            }
        });

        jTableFact.setModel(myModel);
        jTableFact.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFactMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableFact);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonCreerFacture)
                        .addGap(5, 5, 5)
                        .addComponent(jButtonClotureFacture)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClotureFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreerFacture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonClotureFacture, jButtonCreerFacture});

        jPanelVen.add(jPanel2);

        jTableLV.setModel(moModel);
        jTableLV.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jTableLV);

        jButtonAjoutLigneVente.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAjoutLigneVente.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jButtonAjoutLigneVente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones/Add.png"))); // NOI18N
        jButtonAjoutLigneVente.setText("AjoutLigneVente");
        jButtonAjoutLigneVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutLigneVenteActionPerformed(evt);
            }
        });

        jButtonSupprimerLignevent.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSupprimerLignevent.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButtonSupprimerLignevent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprim.png"))); // NOI18N
        jButtonSupprimerLignevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerLigneventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAjoutLigneVente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSupprimerLignevent, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjoutLigneVente)
                    .addComponent(jButtonSupprimerLignevent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAjoutLigneVente, jButtonSupprimerLignevent});

        jPanelVen.add(jPanel1);

        getContentPane().add(jPanelVen, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
       
        JFrame parent = (JFrame)(this.getDesktopPane().getTopLevelAncestor());
        new JDClient(parent, "INSERTION DU CLIENT");

        refreshModelcli();

    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        
        if (jTableClients.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null,"Sélectionnez d'abord un client svp !","Gestion Pharm",JOptionPane.INFORMATION_MESSAGE);
        else {
           JFrame parent = (JFrame)(JIFVente.super.getDesktopPane().getTopLevelAncestor());
            
           Client cli= miModel.getMyList(jTableClients.getSelectedRow());
           
           new JDClient(parent, "MODIFICATION CLIENT",cli);
           
           refreshModelcli();
            
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
       
        if (jTableClients.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null,"Sélectionnez d'abord un client svp !","Gestion Pharm",JOptionPane.INFORMATION_MESSAGE);
        else {
            int rep = JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer le client ?" ,"Gestion Pharm", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION)
            if(daoCli.deleteClient((Integer)miModel.getValueAt(jTableClients.getSelectedRow(),0))){
                  refreshModelcli();
                JOptionPane.showMessageDialog(null, "Client est supprimé avec Succès !"+"\n"+
                    "\n"+"", "Succès", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Une erreur s'est produite lors de la suppression !"+"\n"+
                    "\n"+"", "ERREUR", JOptionPane.ERROR_MESSAGE);
            }

          
           
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jComboBoxRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRechActionPerformed
        
        if(!jComboBoxRech.getSelectedItem().toString().equals("<Tous>".toString()))
        {
            nomC="";
            nomV="";
            cpV="";
        }
        this.rechAll();

    }//GEN-LAST:event_jComboBoxRechActionPerformed

    private void jComboBoxFiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltreActionPerformed
        
        this.rechAll();
    }//GEN-LAST:event_jComboBoxFiltreActionPerformed

    private void selectClientFactRow(){
        if (jTableClients.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null,"Sélectionnez d'abord un client svp !","Gestion Pharm",JOptionPane.INFORMATION_MESSAGE);
        else {
            facture = myModel.getMyList(jTableFact.getSelectedRow()); 
            moModel.setMyList(daoLv.selectLigneVenteParNumfacture(facture.getNumFacture()));       
        }
    }
    private void jTableClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientsMouseClicked
       
        facture = null;
       cl= miModel.getMyList(jTableClients.getSelectedRow());
       myModel.setMyList(daoFact.selectFactureNumCli(cl.getNumCli()));
       moModel.setMyList(new ArrayList<>());//vider la list de lV
       
    }//GEN-LAST:event_jTableClientsMouseClicked

    private void jButtonAjoutLigneVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutLigneVenteActionPerformed
          
        JFrame parent = (JFrame)(this.getDesktopPane().getTopLevelAncestor());
        
        if (cl != null && facture != null){
            new JDLigneVente(parent, "Insertion ligne de Vente",ltv,cl,prod, facture);
            
            moModel.setMyList(daoLv.selectLigneVenteParNumfacture(facture.getNumFacture()));
            moModel.refresh();
            int LigneChoisi = jTableFact.getSelectedRow();
            myModel.refresh();
            jTableFact.setRowSelectionInterval(LigneChoisi, LigneChoisi);
            
        } else {
            JOptionPane.showMessageDialog(null,"Veuillez sélectionner une facture.","Gestion Pharm",JOptionPane.INFORMATION_MESSAGE); 
        }
        
    }//GEN-LAST:event_jButtonAjoutLigneVenteActionPerformed

    private void jButtonSupprimerLigneventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerLigneventActionPerformed
        if (jTableLV.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null,"Sélectionnez d'abord une ligne de vente svp !","Gestion Pharm",JOptionPane.INFORMATION_MESSAGE);
        else {
            String qte = JOptionPane.showInputDialog(null,"Veuillez indiquez la quantité a retiré.","Gestion Pharm", JOptionPane.INFORMATION_MESSAGE); 
            int qteR = Integer.valueOf(qte);
                    
            LigneVente lv = moModel.getMyList(jTableLV.getSelectedRow()); 
            
            
            if(qteR >= lv.getQuantite_vente()){
                lv.setQuantite_vente(0);
                daoLv.deleteLigneVente(lv);                
            }else{
                lv.setQuantite_vente(lv.getQuantite_vente() - qteR);
                System.out.println("Nouvelle quatité : " + lv.getQuantite_vente());
                daoLv.updateVentlignesQuantité(lv);
            }
            float sommeFacture=0;
                for (LigneVente l : moModel.getMyList()){
                    sommeFacture+=(float)((l.getPrix()*(l.getTva()+1))*l.getQuantite_vente());
                }
                facture.setPaye(sommeFacture);
                daoFact.updateFacture(facture); 
                
            moModel.setMyList(daoLv.selectLigneVenteParNumfacture(facture.getNumFacture()));
            int LigneChoisi = jTableFact.getSelectedRow();
            myModel.refresh();
            jTableFact.setRowSelectionInterval(LigneChoisi, LigneChoisi);
        }
    }//GEN-LAST:event_jButtonSupprimerLigneventActionPerformed

    private void jButtonCreerFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerFactureActionPerformed
    
        if (jTableClients.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null,"Sélectionnez d'abord un client svp !","Gestion Pharm",JOptionPane.INFORMATION_MESSAGE);
        else {
            
            Date now = new Date();
          
            Facture fact = getFacture(now , util.getId_user(),cl.getNumCli() , 0);
            
            daoFact.ajoutFacture(fact);
            myModel.setMyList(daoFact.selectFactureNumCli(cl.getNumCli()));
            moModel.refresh(); 
            jTableFact.setRowSelectionInterval(0, 0);
            selectClientFactRow();            
        }
    }//GEN-LAST:event_jButtonCreerFactureActionPerformed

    private void jButtonClotureFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClotureFactureActionPerformed
        if (jTableFact.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null,"SÃ©lectionnez d'abord une facture !","Gestion Pharm",JOptionPane.INFORMATION_MESSAGE);
        else {
            JFrame parent = (JFrame)(JIFVente.super.getDesktopPane().getTopLevelAncestor());
                Facture v = myModel.getMyList(jTableFact.getSelectedRow());
                new JDFactureClient(parent,"FICHE FACTURE DU CLIENT",v);
        }
    }//GEN-LAST:event_jButtonClotureFactureActionPerformed

    private void jTableFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFactMouseClicked
        selectClientFactRow();
    }//GEN-LAST:event_jTableFactMouseClicked
   
    private void refreshModelcli(){
        miModel.setMyList(daoCli.selectClient());
    }    
    
    //faire la recherche avec le combobox
    private void rechAll(){
        
        String varRech = jComboBoxRech.getSelectedItem().toString();
        String varTitre = jComboBoxFiltre.getSelectedItem().toString();
        
        if(varRech.equals("<Tous>".toString()) && !varTitre.equals("<Tous>".toString()))
        {
           miModel.setMyList(daoCli.selectClientTit(varTitre));
           this.jComboBoxFiltre.setSelectedItem("<Tous>");
          
        }
        
        if(varRech.equals("<Tous>".toString()) && varTitre.equals("<Tous>".toString()))
        {   
           refreshModelcli();
           this.refreshModelcli();
           nomV =""; cpV=""; nomC="";
        }
        
        if(!varRech.equals("<Tous>".toString()) && !varTitre.equals("<Tous>".toString()))
         {
            if(nomV != null && varRech.equals("Ville".toString()))
                miModel.setMyList(daoCli.selectClientVilTit(nomV, varTitre));
            
         }
        
        if(!varRech.equals("<Tous>".toString()) && !varTitre.equals("<Tous>".toString()))
         {
           if(nomC != null && varRech.equals("Nom".toString()))
               miModel.setMyList(daoCli.selectClientNomTit(nomC, varTitre));
          
         }
        
        if(!varRech.equals("<Tous>".toString()) && !varTitre.equals("<Tous>".toString()))
         {
            if(cpV != null && varRech.equals("Code Postal".toString()))
               miModel.setMyList(daoCli.selectClientCpTit(cpV, varTitre));
            
         }
        
        if(!varRech.equals("<Tous>".toString()) && varTitre.equals("<Tous>".toString()))
        {
            if("Code Postal".equals((String)jComboBoxRech.getSelectedItem()))
                {
                    if(cpV.equals("".toString()))
                    {   try{
                         cpV = JOptionPane.showInputDialog(null,"Entrer Le code Postal du client","Code Postal",JOptionPane.QUESTION_MESSAGE);
                         cpV = cpV.trim();            ////ce code permet d'efface les espaces unitiles de fin et debut du nom////
                            }catch(Exception e){
                                
                            }
                    
                         nomC ="";nomV="";
                    }
                    if(cpV != null)
                        miModel.setMyList(daoCli.selectClientCp(cpV));
                }
            else{   
                
                if("Nom".equals((String)jComboBoxRech.getSelectedItem())){
                    if(nomC.equals("".toString()))
                    {
                        try{
                        nomC = JOptionPane.showInputDialog(null,"Entrer Le Nom du client","Nom du Client",JOptionPane.QUESTION_MESSAGE);
                        nomC = nomC.trim();    //il permet d' efface les espace unitiles de fin et debut du nom
                        }catch(Exception e){
                        
                        }
                        cpV ="";nomV="";
                    }
                    if(nomC !=null)
                       miModel.setMyList(daoCli.selectClientNom(nomC));
                }
                else
                {
                    if("Ville".equals((String)jComboBoxRech.getSelectedItem())){
                        if(nomV.equals("".toString()))
                        {
                           try{ 
                           nomV = JOptionPane.showInputDialog(null,"Entrer la ville du client","Ville",JOptionPane.QUESTION_MESSAGE);
                           nomV = nomV.trim();     //il permet d' efface les espaces unitiles de fin et debut du nom
                           }catch(Exception e){
                               
                           }
                           nomC ="";cpV="";
                        }
                        if(nomV !=null)
                             miModel.setMyList(daoCli.selectClientVil(nomV));
                    }
                }
            }
        }
        
    }
    
   
    
    
    public Facture getFacture(Date dateVente,int Id_user,int numCli ,int paye )
    {
        Facture fact = new Facture( );
        try{
           fact.setDateVente(dateVente);
           fact.setId_user(Id_user);
           fact.setNumCli(numCli);
            
           fact.setPaye(paye);
           
        }catch(Exception e)
        {
            
        }
            
        return fact;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjoutLigneVente;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonClotureFacture;
    private javax.swing.JButton jButtonCreerFacture;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JButton jButtonSupprimerLignevent;
    private javax.swing.JComboBox jComboBoxFiltre;
    private javax.swing.JComboBox jComboBoxRech;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCli;
    private javax.swing.JPanel jPanelVen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableClients;
    private javax.swing.JTable jTableFact;
    private javax.swing.JTable jTableLV;
    // End of variables declaration//GEN-END:variables
   
    private IDaoClient daoCli = DaoFactory.getDaoClient();
    private IDaoFacture daoFact = DaoFactory.getDaoFacture(); 
    private IDaoLigneVente daoLv=DaoFactory.getDaoLigneVente();
    private TableModelFacture myModel = new model.TableModelFacture (new ArrayList<>()); // Model facture// Seule la liste des clients est affichée.
    private TableModelClients miModel = new model.TableModelClients (daoCli.selectClient());// model client
    private TableModelLigneVente moModel=new model.TableModelLigneVente(new ArrayList<>());// model ligneVente//Seule la liste des clients est affichée.
    private static String nomV ="", cpV="" , nomC="";
    private static boolean modif = false;
    private Utilisateur util;
    private Client cl;
    private LigneVente lv;
    private LigneVente ltv;
    private Produit prod;
    private Facture facture;
}
